### ISSUE TITLE
Add support for high contrast accessibility setting

### ISSUE THREAD

**Issue by simonmitchell** [3sidedcube/ThunderCloud#187]
## Expected Behaviour

Colours should update when accessibility setting for high contrast colours is changed

## Current Behaviour

Colours aren't updated when the setting is changed

## Possible Solution

Listen for `darkerSystemColorsStatusDidChangeNotification` in various places and refresh UI based on it.

## Context

This is for ADA compliance for the ARC apps.

**Comment by ryanbourneuk** [comment]
Resolved in v1.5.0
