### ISSUE TITLE
Inactive timer text in InlineButtonView is incorrectly coloured.

### ISSUE THREAD

**Issue by ryanbourneuk** [3sidedcube/ThunderCloud#188]
## Expected Behaviour

The button title, when the timer is stopped, should be visible. This would align with the other buttons which do not present a `TimerLink` object.

## Current Behaviour

The button title colour is changed immediately upon the timer stopping to the same colour as the border. This, when in `solidMode` is the same as the background so the text is not visible. This only occurs when the `InlineButtonView` is displaying a `TimerLink` object.

## Possible Solution

Remove
```swift
if let borderColor = layer.borderColor {
  setTitleColor(UIColor(cgColor: borderColor), for: .normal)
}
```

## Steps to Reproduce (for bugs)

1. Have a timer button within a cell.
2. Open the page that contains the cell
3. See that the button does not have text, click on the button to start the timer.
4. See that the timer countdown is visible
5. Click on the button to stop the timer
6. See that the text has vanished

## Your Environment

* ThunderCloud version: v1.4.0

**Comment by simonmitchell** [comment]
Oooooh, I thought this was within the project itself? Does `BRC FA` not override this function?

**Comment by simonmitchell** [comment]
Sorry this is my bad! This is an unnecessary change, I had a stash in BRC FA that overrides these functions to style correctly for solid buttons. ThunderCloud can remain the same as by default it uses non-solid buttons!
