### ISSUE TITLE
Streaming Pages cannot open web views

### ISSUE THREAD

**Issue by ryanbourneuk** [3sidedcube/ThunderCloud#215]
## Expected Behaviour

When tapping on a link that should open a web view, a web view should appear.

## Current Behaviour

A web view does not appear.

## Possible Solution

We should, after checking for the right-most navigation controller, also check to see if the `presentedViewController` is a Streaming Page navigation controller (we can subclass from UINavigationController and check the type at run time).

## Steps to Reproduce (for bugs)

1. Send a push notification to a supported app, which loads a page with a link that should open internally.
2. Tap the link
3. It does nothing

## Context

This is affecting various Storm CMS apps, as when push notifications are sent they may include links that should open in web views.

## Your Environment

* ThunderCloud version: v1.5.1

**Comment by simonmitchell** [comment]
There is wider scope here, we've fixed this for one particular case but it also seems to be an issue for example in the modally presented toolkit in the prep apps!
